# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hacker Wizard
email: feedback@hackerwizard.com
address: 276 Fifth Avenue, New York 10001
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jbond14.github.io/world" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-236316587-1
twitter_username: 
github_username: 
instagram_username:  
utterances: jbond14/world
rss: feed.xml
author: tnwp
logo: /assets/images/logo.png
fixed: false
og_image: /assets/images/opengraph.png

# Build settings
# theme: minima

# theme: bombpress

# jekyll-archives:
#   enabled: all
#   layout: archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'

plugins: 
  - jekyll-feed
  # - jekyll-archives
  - jekyll-seo-tag
  # - jekyll-news-sitemap
  - jekyll-sitemap
  - jekyll-github-metadata
  # - jekyll-spaceship
  - jekyll-octicons
  # - jekyll-timeago
  - jekyll-mentions
  - jekyll-gist 
  # - jekyll-avatar 

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/
  authors:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/ 